#!/usr/bin/env python3
"""Generate LiquidGlassIconPreviews.gen.h from per-icon preview PNGs.

Reads the icon registry from ../icons.json (the single source of truth for
the Liquid Glass icon set) and the preview PNGs from
../icons/<id>/{default,dark,clear-light,clear-dark}.png.

Emits three things into the header:

  1. `kLGPreviewEntries[]`     — base64-encoded PNGs, decoded lazily by
                                 the tweak and cached forever.
  2. `kLGIconRows[]`           — (iconID, displayName) pairs for the icon
                                 picker, in registry order.
  3. `kLGPrimaryIconID`        — the icon ID treated as the bundle's
                                 default (no alternate icon set).
"""
from __future__ import annotations

import base64
import json
import os
import sys

VARIANTS = ["default", "dark", "clear-light", "clear-dark"]


def sanitize(name: str) -> str:
    return name.replace("-", "_")


def chunked(s: str, width: int = 76):
    for i in range(0, len(s), width):
        yield s[i:i + width]


def load_registry(repo_lg_dir: str) -> dict:
    registry_path = os.path.join(repo_lg_dir, "icons.json")
    with open(registry_path, "r") as fp:
        registry = json.load(fp)
    if "icons" not in registry or "primaryIconID" not in registry:
        print(f"invalid registry at {registry_path}", file=sys.stderr)
        sys.exit(1)
    return registry


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate_previews_header.py <output_header_path>", file=sys.stderr)
        return 2

    out_path = sys.argv[1]
    scripts_dir = os.path.dirname(os.path.abspath(__file__))
    lg_dir = os.path.abspath(os.path.join(scripts_dir, ".."))
    registry = load_registry(lg_dir)

    rows = []
    arrays = []
    icon_meta = []   # [(id, displayName)]

    for entry in registry["icons"]:
        icon_id = entry["id"]
        display_name = entry.get("displayName", icon_id)
        icon_meta.append((icon_id, display_name))

        previews_dir = os.path.join(lg_dir, "icons", icon_id)
        for variant in VARIANTS:
            src = os.path.join(previews_dir, f"{variant}.png")
            if not os.path.isfile(src):
                print(f"missing preview asset: {src}", file=sys.stderr)
                return 1

            with open(src, "rb") as fp:
                data = fp.read()

            b64 = base64.b64encode(data).decode("ascii")
            symbol = f"kLGPreviewB64_{sanitize(icon_id)}_{sanitize(variant)}"
            # Emit one C string literal per chunked line. Adjacent string
            # literals concatenate at compile time, so this is a single
            # const char *.
            literal_lines = "\n".join(f'    "{chunk}"' for chunk in chunked(b64))
            arrays.append(
                f"static const char {symbol}[] =\n{literal_lines};\n"
            )
            rows.append((icon_id, variant, symbol, len(data)))

    with open(out_path, "w") as fp:
        fp.write("// Auto-generated by liquid-glass/scripts/generate_previews_header.py.\n")
        fp.write("// Do not edit by hand. Regenerate with `make lg-previews`.\n")
        fp.write("#pragma once\n\n")
        fp.write("#include <stddef.h>\n\n")

        for blob in arrays:
            fp.write(blob)
            fp.write("\n")

        fp.write("typedef struct {\n")
        fp.write("    const char *iconID;\n")
        fp.write("    const char *variant;\n")
        fp.write("    const char *base64;\n")
        fp.write("    size_t decodedLength;\n")
        fp.write("} LGPreviewEntry;\n\n")

        fp.write("static const LGPreviewEntry kLGPreviewEntries[] = {\n")
        for icon_id, variant, symbol, decoded_length in rows:
            fp.write(f'    {{ "{icon_id}", "{variant}", {symbol}, {decoded_length} }},\n')
        fp.write("};\n\n")
        fp.write(f"static const size_t kLGPreviewEntryCount = {len(rows)};\n\n")

        fp.write("typedef struct {\n")
        fp.write("    const char *iconID;\n")
        fp.write("    const char *displayName;\n")
        fp.write("} LGIconRowEntry;\n\n")

        fp.write("static const LGIconRowEntry kLGIconRowEntries[] = {\n")
        for icon_id, display_name in icon_meta:
            # Escape any embedded quotes in the display name to keep the
            # generated C literal well-formed.
            safe_name = display_name.replace('\\', '\\\\').replace('"', '\\"')
            fp.write(f'    {{ "{icon_id}", "{safe_name}" }},\n')
        fp.write("};\n\n")
        fp.write(f"static const size_t kLGIconRowEntryCount = {len(icon_meta)};\n\n")

        primary = registry["primaryIconID"]
        fp.write(f'static const char *const kLGPrimaryIconIDCString = "{primary}";\n')

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
